<?php

return [
    'url_api' => env('URL_API_SERVICES'),
    'url_auth_api'=> env('URL_API_SERVICES').'auth/login',
    'sincFechaHora' => env('SINCRONIZAR_FECHA_HORA'),
    'sincTiposFactura' => env('SINCRONIZAR_TIPOS_FACTURA'),
    'sincMensajesServicios' => env('SINCRONIZAR_MENSAJES_SERVICIOS'),
    'sincEventosSignificativos' => env('SINCRONIZAR_EVENTOS_SIGNIFICATIVOS'),
    'sincTipoPV' => env('SINCRONIZAR_TIPO_PV'),
    'sincProductosServicios' => env('SINCRONIZAR_PRODUCTOS_SERVICIOS'),
    'sincTipoMoneda' => env('SINCRONIZAR_TIPO_MONEDA'),
    'sincActividades' => env('SINCRONIZAR_ACTIVIDADES'),
    'sincTipoEmision' => env('SINCRONIZAR_TIPO_EMISION'),
    'sincTipoDocumentoIdentidad' => env('SINCRONIZAR_TIPO_DOCUMENTO_IDENTIDAD'),
    'sincLeyendas' => env('SINCRONIZAR_LEYENDAS'),
    'sincTipoMetodoPago' => env('SINCRONIZAR_TIPO_METODO_PAGO'),
    'sincUnidadMedida' => env('SINCRONIZAR_UNIDAD_MEDIDA'),
    'sincPaisOrigen' => env('SINCRONIZAR_PAIS_ORIGEN'),
    'sincTipoHabitacion' => env('SINCRONIZAR_TIPO_HABITACION'),
    'sincMotivoAnulacion' => env('SINCRONIZAR_MOTIVO_ANULACION'),
    'sincTipoDocumentoSector' => env('SINCRONIZAR_TIPO_DOCUMENTO_SECTOR'),
    'sincActividadesDocumentoSector' => env('SINCRONIZAR_ACTIVIDADES_DOCUMENTO_SECTOR'),
    'email_api' => env('API_AUTH_EMAIL'),
    'password_api' => env('API_AUTH_PASSWORD'),
];
